[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  # Variables d'environnement pour le build
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Configuration spécifique pour Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuration pour Prisma
[build.processing]
  skip_processing = false

# Optimisations de build
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Redirections pour Next.js App Router
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
