[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Plugin Next.js - laisser gérer TOUT le routing
[[plugins]]
  package = "@netlify/plugin-nextjs"
